-- Generated by HyprMod

-- Settings
hl.config({
    cursor = {
        enable_hyprcursor = true,
        hide_on_key_press = true,
        no_hardware_cursors = 1,
        no_warps = true,
    },
    decoration = {
        blur = {
            enabled = true,
            passes = 2,
            special = true,
            xray = false,
        },
        dim_strength = 0.0,
    },
    dwindle = {
        force_split = 2,
        smart_split = false,
    },
    ecosystem = {
        enforce_permissions = true,
        no_donation_nag = true,
    },
    general = {
        border_size = 5,
        gaps_in = 5,
        gaps_out = 5,
        layout = "dwindle",
    },
    input = {
        touchpad = {
            clickfinger_behavior = false,
        },
    },
    master = {
        new_on_active = "before",
        new_status = "master",
        orientation = "left",
        smart_resizing = false,
    },
    misc = {
        animate_manual_resizes = true,
        animate_mouse_windowdragging = true,
        disable_splash_rendering = true,
    },
})
