-- Generated by nwg-displays on 2026-05-17 at 03:12:07. Do not edit manually.
hl.monitor({
    output = "desc:Lenovo Group Limited 0x403A",
    mode = "1920x1200@60.0",
    position = "10640x240",
    scale = 1.0,
})
hl.monitor({
    output = "desc:Dell Inc. DELL U2515H 9X2VY69U12NL",
    mode = "2560x1440@59.95",
    position = "8080x0",
    scale = 1.0,
})
