###############################
### VARIABLES & SETTINGS ###
###############################

# Main modifier key
$mainMod = ALT
$INPUT_DEVICES_ENABLED = 1

# Programs
$terminal = ghostty
$fileManager = yazi
$menu = rofi -show drun

# Styling variables
$border_size = 5
$gaps_in = 4
$gaps_out = 10
$rounding = 0
$animation_speed = 1

# Colors
$color_border_active = rgba(d4d0c8ff)
$color_border_inactive = rgba(7a7a7aff)
$color_text = 0x000000
