cursor #8ce68f
cursor_text_color #0a5e89
selection_foreground #0a5e89
selection_background #b6efb8

url_color #f1f3f1
visual_bell_color #d8e1db
bell_border_color #c8d3bb

active_border_color #b1f4b4
inactive_border_color #b6efb8

foreground #6ddfff
background #084e71

active_tab_foreground #0a5e89
active_tab_background #74dbf8
inactive_tab_foreground #7cd7f0
inactive_tab_background #0c6ea1

color0 #f9cb28
color8 #e8b606
color1 #f1f3f1
color9 #f0f4f0
color2 #d8e1db
color10 #d8e1dd
color3 #c8d3bb
color11 #e0e7d9
color4 #b6efb8
color12 #e0f8e1
color5 #f7ca0b
color13 #f7f10b
color6 #96e395
color14 #8fea8e
color7 #7be3b5
color15 #a5eccd