cursor #798da6
cursor_text_color #252126
selection_foreground #252126
selection_background #98a7ba

url_color #c9c6e2
visual_bell_color #a8acca
bell_border_color #a0a0a0

active_border_color #8fa6c3
inactive_border_color #98a7ba

foreground #a078c4
background #181518

active_tab_foreground #252126
active_tab_background #9f82ba
inactive_tab_foreground #9f8bb1
inactive_tab_background #322d34

color0 #8285b9
color8 #6165a7
color1 #c9c6e2
color9 #c6c2e6
color2 #a8acca
color10 #a9a8ca
color3 #a0a0a0
color11 #b9b9b9
color4 #98a7ba
color12 #b6c1cf
color5 #90869b
color13 #93869b
color6 #8383bf
color14 #7a7ac8
color7 #5e8ad0
color15 #85a7dc