cursor #ffe0e0
cursor_text_color #1d6d99
selection_foreground #1d6d99
selection_background #ffffff

url_color #dbe7f7
visual_bell_color #90d9ff
bell_border_color #b7effb

active_border_color #ffffff
inactive_border_color #ffffff

foreground #5dfcff
background #195e84

active_tab_foreground #1d6d99
active_tab_background #65f4f7
inactive_tab_foreground #6decef
inactive_tab_background #217cae

color0 #abf2ff
color8 #78eaff
color1 #dbe7f7
color9 #d9e7f9
color2 #90d9ff
color10 #90c7ff
color3 #b7effb
color11 #d4ffff
color4 #ffffff
color12 #ffffff
color5 #ffdcff
color13 #ffdcf9
color6 #7af9ff
color14 #7af9ff
color7 #84f7ff
color15 #b7faff